name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 23f1003133@ds.study.iitm.ac.in
        run: echo "Hello World!"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: create a file and push
        run: |
          echo "Hello World" >> hello.txt
          git config --local user.email "23f1003133@ds.study.iitm.ac.in"
          git config --local user.name "Shivam Kumar"
          git add hello.txt
          git commit -m "Updated hello.txt [skip ci]" || exit 0
          git push

